---
# tasks file for desktop
- name: Install pipewire first
  community.general.pacman:
    name: pipewire
    state: present

- name: Install wireplumber as dependency of pipewire-alsa
  community.general.pacman:
    name: wireplumber
    state: present
    extra_args: "--asdeps"
