---
# tasks file for desktop
- name: Install pipewire first
  community.general.pacman:
    name: "{{ pipe_wire }}"
    state: present

- name: Check if gdm in installed
  ansible.builtin.stat:
    path: /usr/bin/gdm
  register: stat_gdm

- name: Install gnome group
  community.general.pacman:
    name: gnome
    state: present
  when: not stat_gdm.stat.exists

- name: Remove unwanted gnome apps
  community.general.pacman:
    name: "{{ unwanted_gui_apps }}"
    state: absent
    extra_args: "--recursive"

- name: Install other apps
  community.general.pacman:
    name: "{{ other_gui_apps }}"
    state: present

- name: Install other gui AUR
  kewlfft.aur.aur:
    name: "{{ other_gui_aur }}"
    use: makepkg
    state: present
  become: no

- name: Enable and start gdm
  ansible.builtin.service:
    name: gdm
    enabled: yes
    state: started

- name: Include task for box guest
  ansible.builtin.include_tasks: vbox.yml
  when: vbox_guest is defined
