---
# tasks file for desktop
- name: Install pipewire first
  community.general.pacman:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
    state: present

- name: Install gnome vlc and strawberry
  community.general.pacman:
    name: gnome
    state: present

