---
# tasks file for desktop
- name: Install pipewire first
  community.general.pacman:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
    state: present
