---
- name: Install guest additions
  community.general.pacman:
    name: "{{ vbox_guest }}"
    state: present

- name: Enable and start vboxservice
  ansible.builtin.service:
    name: vboxservice
    enabled: yes
    state: started

- name: Ignore updates for vbox guest
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^IgnorePkg   ="
    insertafter: "^#IgnorePkg"
    line: "IgnorePkg   = {{ ignore_package }}"
