---
# handlers file for sync_time
- name: Start timesyncd service
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: yes
    state: started

- name: Enable ntp
  ansible.builtin.command: timedatectl set-ntp true
